package com.cts.pensionerDetail.service;

import static org.junit.Assert.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.io.IOException;
import java.text.ParseException;

import org.junit.jupiter.api.DisplayName;
//import org.junit.Rule;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

import org.springframework.boot.test.context.SpringBootTest;

import com.cts.pensionerDetail.exception.NotFoundException;
import com.cts.pensionerDetail.model.BankDetails;
import com.cts.pensionerDetail.model.PensionerDetails;
import com.cts.pensionerDetail.util.DateUtil;


@SpringBootTest
class PensionDetailServiceTest {

	@Autowired
	PensionerDetailService pensionerDetailService;

	@Test
	@DisplayName(value="Method to test Pensioner Detail Service Object is null or not")
	void test_PensionDetailServiceObject() {
		assertNotNull(pensionerDetailService);
	}


	@Test
	@DisplayName(value = "Method to test whether details provided by valid aadhaar card number is correct or not")
	void test_validateCorrectAadhaarCardDetails()
			throws IOException, NotFoundException, NumberFormatException, ParseException, NullPointerException {
		final String aadhaarNumber = "982521289534";

		PensionerDetails pensionerDetail = new PensionerDetails("982521289534", DateUtil.parseDate("11-02-2009"),
				"XZWE3HWLXR", 32940, 6252, "self", new BankDetails("Goldward Financial Group", 88980359, "public"));
		assertEquals(pensionerDetailService.getPensionerDetailByAadhaarNumber(aadhaarNumber).getPan(), pensionerDetail.getPan());
		assertEquals(pensionerDetailService.getPensionerDetailByAadhaarNumber(aadhaarNumber).getBank().getAccountNumber(),
				pensionerDetail.getBank().getAccountNumber());
	}

	@Test
	@DisplayName(value = "Method to test whether details provided by invalid aadhaar card number or not")
	void test_validateInCorrectAadhaarCardDetails() {
		final String aadhaarNumber = "12345678";

		NotFoundException exception = assertThrows(NotFoundException.class,
				() -> pensionerDetailService.getPensionerDetailByAadhaarNumber(aadhaarNumber));
		assertEquals(exception.getMessage(), "AADHAAR_NUMBER_NOT_FOUND");
		assertNotNull(exception);
	}
}
